### ISSUE TITLE
Weird font

### ISSUE THREAD

**Issue by jozsaVilmos** [moyaiu/OldCord#32]
Every text on my Discord is this weird font. If I comment out the theme it reverts back to normal.

https://i.postimg.cc/3Nymk3XV/e9ddbc7f91372b15d9c917b7a718258a.png

**Comment by vylryna** [comment]
im probably very wrong but I think it's because discord's replacing the font with their new custom one "gg sans", so it might be interfering idk

**Comment by vylryna** [comment]
I guess the Whitney font got removed from discord then, because it isn't working for me either. Probably gonna have to import it from somewhere on the internet

**Comment by DaMoyai** [comment]
> I guess the Whitney font got removed from discord then, because it isn't working for me either. Probably gonna have to import it from somewhere on the internet

yeah, luckily i got an exact backup of these files

**Comment by vylryna** [comment]
nice, the way I fixed it was I just found a zip file containing all of the whitney files [here](https://www.cufonfonts.com/font/whitney-2), installed them all, then just added this code to my custom css and it worked:

```css
:root {
    --font-primary: "Whitney", "Noto Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    --font-display: "Whitney", "Noto Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    --font-headline: "Whitney", "Noto Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

im not an expert on css or anything so im not sure how you import custom fonts from a url lol
